name: scoped_example
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:


  cupertino_icons: ^0.1.2
  scoped_model: "^0.2.0"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:

    - assets/logo.jpg
